Estoque_Pessoal/Controllers/EstoquesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Estoque_Pessoal.Models;
using Estoque_Pessoal.DAL;

namespace Estoque_Pessoal.Controllers
{
    [Authorize]
    public class EstoquesController : Controller
    {
        private ModelosContainer db = new ModelosContainer();
        private EstoqueItemDAO estoqueItemDAO = new EstoqueItemDAO();
        private EstoqueDAO estoqueDAO = new EstoqueDAO();

        // GET: Estoques
        public ActionResult Index()
        {
            return View(db.EstoqueSet.Where(x => x.Cliente.Login == User.Identity.Name).ToList());
        }

        // GET: Estoques/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Estoque estoque = db.EstoqueSet.Find(id);
            if (estoque == null)
            {
                return HttpNotFound();
            }
            return View(estoque);
        }

        // GET: Estoques/Create
        public ActionResult Create()
        {
            List<Item> lista = db.ItemSet.ToList();
            if (lista != null)
                ViewBag.lista = new SelectList(lista, "id", "nome", null);

            Estoque viewModel = new Estoque();
            viewModel.EstoqueItem = new EstoqueItem();
            viewModel.EstoqueItem.Item = new Item();
            viewModel.EstoqueItem.Quantidade = 1;
            return View(viewModel);
        }

        // POST: Estoques/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create( Estoque estoque)
        {
            if (ModelState.IsValid)
            {
                estoque.Cliente = RetornarLogado();
                if (estoque.Cliente != null)
                {
                    //Verifica se já existe um item de estoque com o mesmo produto para o mesmo usuário
                    if (db.EstoqueSet.Where(x => x.Cliente.Id == estoque.Cliente.Id && x.EstoqueItem.Item.Id == estoque.EstoqueItem.Id).FirstOrDefault() == null)
                    {
                        estoque.EstoqueItem.Id = estoqueItemDAO.Add(estoque.EstoqueItem);
                        estoqueDAO.Add(estoque);
                    }
                    else
                    {
                        TempData["Error"] = "O item já existe no estoque!";
                        ModelState.AddModelError("", "O item já existe no estoque!");
                    }
                }
                else
                {
                    TempData["Error"] = "Usuário inválido!";
                    ModelState.AddModelError("", "Usuário inválido!");
                }
                
                return RedirectToAction("Index");
            }

            return View(estoque);
        }

        public Cliente RetornarLogado()
        {
            Cliente c = null;
            c = db.ClienteSet.Where(x => x.Login == User.Identity.Name).FirstOrDefault();
            return c;
        }

        // GET: Estoques/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Estoque estoque = db.EstoqueSet.Find(id);
            if (estoque == null)
            {
                return HttpNotFound();
            }
            return View(estoque);
        }

        // POST: Estoques/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id")] Estoque estoque)
        {
            if (ModelState.IsValid)
            {
                db.Entry(estoque).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(estoque);
        }

        // GET: Estoques/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Estoque estoque = db.EstoqueSet.Find(id);
            if (estoque == null)
            {
                return HttpNotFound();
            }
            return View(estoque);
        }

        // POST: Estoques/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            
            Estoque estoque = db.EstoqueSet.Find(id);
            EstoqueItem es = db.EstoqueItemSet.Find(estoque.EstoqueItem.Id);
            db.EstoqueSet.Remove(estoque);
            db.EstoqueItemSet.Remove(es);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult EditarQuantidade(int itemEstoqueId, int quantidade)
        {
            EstoqueItem estoque = db.EstoqueItemSet.Where(x => x.Id == itemEstoqueId).FirstOrDefault();
            estoque.Quantidade = quantidade;
            db.Entry(estoque).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Estoque_Pessoal/Controllers/ItensController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Estoque_Pessoal.Models;

namespace Estoque_Pessoal.Controllers
{
    public class ItensController : Controller
    {
        private ModelosContainer db = new ModelosContainer();

        // GET: Itens
        public ActionResult Index()
        {
            return View(db.ItemSet.ToList());
        }

        // GET: Itens/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.ItemSet.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }


        // GET: Itens/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Itens/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Nome")] Item item)
        {
            if (ModelState.IsValid)
            {
                db.ItemSet.Add(item);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(item);
        }

        // GET: Itens/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.ItemSet.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // POST: Itens/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nome")] Item item)
        {
            if (ModelState.IsValid)
            {
                db.Entry(item).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(item);
        }

        // GET: Itens/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.ItemSet.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // POST: Itens/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Item item = db.ItemSet.Find(id);
            db.ItemSet.Remove(item);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Estoque_Pessoal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @*<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">*@
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container-fluid  col-xs-12 col-sm-8 col-lg-8">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                   @Html.ActionLink("Meu estoque", "Index", "Estoques", null, new { @class = "navbar-brand" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Itens cadastrados", "Index", "Itens", null, new { @class = "navbar-brand" })
                    
                </li>
                <li>
                    @Html.ActionLink("Meu cadastro", "Edit", "Clientes", null, new { @class = "navbar-brand" })
                </li>
                <li>
                    @Html.ActionLink("Sair", "Logoff", "Clientes", null, new { @class = "navbar-brand" })
                </li>
                <li style="padding-left:250px;">
                    Bem vindo, @User.Identity.Name
                </li>
                   
                </ul>
</div>
    </nav>
       
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p style="text-align:center;">&copy; @DateTime.Now.Year - Meu Estoque</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Estoque_Pessoal/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                
            </div>
            <div class="navbar-collapse collapse">

            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p style="margin-left:350px;">&copy; @DateTime.Now.Year - Meu Estoque</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>