Estoque_Pessoal/Models/Estoque.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Estoque_Pessoal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estoque
    {
        public int Id { get; set; }
        public int Quantidade { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Item Item { get; set; }
    }
}

Estoque_Pessoal/Controllers/EstoqueItensController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Estoque_Pessoal.Models;

namespace Estoque_Pessoal.Controllers
{
    public class EstoqueItensController : Controller
    {
        private ModelosContainer db = new ModelosContainer();

        // GET: EstoqueItens
        public ActionResult Index()
        {
            return View(db.EstoqueItemSet.ToList());
        }

        // GET: EstoqueItens/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EstoqueItem estoqueItem = db.EstoqueItemSet.Find(id);
            if (estoqueItem == null)
            {
                return HttpNotFound();
            }
            return View(estoqueItem);
        }

        // GET: EstoqueItens/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: EstoqueItens/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Quantidade")] EstoqueItem estoqueItem)
        {
            if (ModelState.IsValid)
            {
                db.EstoqueItemSet.Add(estoqueItem);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(estoqueItem);
        }

        // GET: EstoqueItens/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EstoqueItem estoqueItem = db.EstoqueItemSet.Find(id);
            if (estoqueItem == null)
            {
                return HttpNotFound();
            }
            return View(estoqueItem);
        }

        // POST: EstoqueItens/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Quantidade")] EstoqueItem estoqueItem)
        {
            if (ModelState.IsValid)
            {
                db.Entry(estoqueItem).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index","Estoques");
            }
            return View(estoqueItem);
        }

        // GET: EstoqueItens/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EstoqueItem estoqueItem = db.EstoqueItemSet.Find(id);
            if (estoqueItem == null)
            {
                return HttpNotFound();
            }
            return View(estoqueItem);
        }

        // POST: EstoqueItens/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            EstoqueItem estoqueItem = db.EstoqueItemSet.Find(id);
            db.EstoqueItemSet.Remove(estoqueItem);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Estoque_Pessoal/Controllers/EstoquesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Estoque_Pessoal.Models;
using Estoque_Pessoal.DAL;

namespace Estoque_Pessoal.Controllers
{
    [Authorize]
    public class EstoquesController : Controller
    {
        private ModelosContainer db = new ModelosContainer();
        private EstoqueItemDAO estoqueItemDAO = new EstoqueItemDAO();
        private EstoqueDAO estoqueDAO = new EstoqueDAO();

        // GET: Estoques
        public ActionResult Index()
        {
            return View(db.EstoqueSet.Where(x => x.Cliente.Login == User.Identity.Name).ToList());
        }

        // GET: Estoques/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Estoque estoque = db.EstoqueSet.Find(id);
            if (estoque == null)
            {
                return HttpNotFound();
            }
            return View(estoque);
        }

        // GET: Estoques/Create
        public ActionResult Create()
        {
            List<Item> lista = db.ItemSet.ToList();
            if (lista != null)
                ViewBag.lista = new SelectList(lista, "id", "nome", null);

            Estoque viewModel = new Estoque();
            viewModel.EstoqueItem = new EstoqueItem();
            viewModel.EstoqueItem.Item = new Item();
            viewModel.EstoqueItem.Quantidade = 1;
            return View(viewModel);
        }

        // POST: Estoques/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create( Estoque estoque)
        {
            if (ModelState.IsValid)
            {
                estoque.Cliente = RetornarLogado();
                if (estoque.Cliente != null)
                {
                    //Verifica se já existe um item de estoque com o mesmo produto para o mesmo usuário
                    if (db.EstoqueSet.Where(x => x.Cliente.Id == estoque.Cliente.Id && x.EstoqueItem.Item.Id == estoque.EstoqueItem.Id).FirstOrDefault() == null)
                    {
                        estoque.EstoqueItem.Id = estoqueItemDAO.Add(estoque.EstoqueItem);
                        estoqueDAO.Add(estoque);
                    }
                    else
                    {
                        TempData["Error"] = "O item já existe no estoque!";
                        ModelState.AddModelError("", "O item já existe no estoque!");
                    }
                }
                else
                {
                    TempData["Error"] = "Usuário inválido!";
                    ModelState.AddModelError("", "Usuário inválido!");
                }
                
                return RedirectToAction("Index");
            }

            return View(estoque);
        }

        public Cliente RetornarLogado()
        {
            Cliente c = null;
            c = db.ClienteSet.Where(x => x.Login == User.Identity.Name).FirstOrDefault();
            return c;
        }

        // GET: Estoques/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Estoque estoque = db.EstoqueSet.Find(id);
            if (estoque == null)
            {
                return HttpNotFound();
            }
            return View(estoque);
        }

        // POST: Estoques/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id")] Estoque estoque)
        {
            if (ModelState.IsValid)
            {
                db.Entry(estoque).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(estoque);
        }

        // GET: Estoques/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Estoque estoque = db.EstoqueSet.Find(id);
            if (estoque == null)
            {
                return HttpNotFound();
            }
            return View(estoque);
        }

        // POST: Estoques/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            
            Estoque estoque = db.EstoqueSet.Find(id);
            EstoqueItem es = db.EstoqueItemSet.Find(estoque.EstoqueItem.Id);
            db.EstoqueSet.Remove(estoque);
            db.EstoqueItemSet.Remove(es);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult EditarQuantidade(int itemEstoqueId, int quantidade)
        {
            EstoqueItem estoque = db.EstoqueItemSet.Where(x => x.Id == itemEstoqueId).FirstOrDefault();
            estoque.Quantidade = quantidade;
            db.Entry(estoque).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Estoque_Pessoal/Views/Estoques/Create.cshtml
@model Estoque_Pessoal.Models.Estoque

@{
    ViewBag.Title = "Adicionar Item ao Estoque";
    var lista = ViewBag.lista as SelectList;
}

<h2>Adicionar um item ao Estoque</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Estoque</h4>
        <hr />
        <div class="form-group">
            @Html.LabelFor(model => model.Cliente, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
           
                @Html.DropDownListFor(m => m.EstoqueItem.Id,
                lista.Select(option => new SelectListItem
                {
                    Text = option.Text,
                    Value = option.Value
                }), 
                htmlAttributes: new {
                    @class = "form-control",
                    @style = "width:300px;",
                    @id = "dropdown",
                    @name = "dropdown" })

                @Html.ValidationMessageFor(model => model.Cliente, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EstoqueItem.Quantidade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EstoqueItem.Quantidade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EstoqueItem.Quantidade, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Adicionar item ao estoque" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar ao estoque", "Index")
</div>

Estoque_Pessoal/Views/Estoques/Delete.cshtml
@model Estoque_Pessoal.Models.Estoque

@{
    ViewBag.Title = "Delete";
}

<h2>Excluir</h2>

<h3>Tem certeza que deseja remover do estoque?</h3>
<div>
    <h4>Meu estoque</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.EstoqueItem.Item.Nome)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EstoqueItem.Item.Nome)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EstoqueItem.Quantidade)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EstoqueItem.Quantidade)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Excluir" class="btn btn-default" /> |
            @Html.ActionLink("Voltar ao estoque", "Index")
        </div>
    }
</div>

Estoque_Pessoal/Views/Estoques/Index.cshtml
@model IEnumerable<Estoque_Pessoal.Models.Estoque>

@{
    ViewBag.Title = "Meu estoque";
}

@* //Se o objeto enviado pelo controller for diferente de nulo e a string de erro for diferente de vazio, exibir mensagem na tela *@
@if (TempData["Error"] != null)
{
    if ((string)TempData["Error"] != "")
    {
        <div class="alert">
            <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
            @TempData["Error"].ToString()
        </div>
    }
}

<h2>Meu estoque</h2>

<p>
    @Html.ActionLink("Adicionar item ao meu estoque", "Create")
</p>
<table class="table table-striped table-hover table-bordered">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.EstoqueItem.Item.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EstoqueItem.Quantidade)
        </th>
        <th>
            Ações   
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.EstoqueItem.Item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EstoqueItem.Quantidade)
        </td>
        <td>
            @Html.ActionLink("Editar Quantidade", "Edit", "EstoqueItens", new { id = item.EstoqueItem.Id },null) |
            @Html.ActionLink("Excluir","Delete", new { id = item.Id })
        </td>
    </tr>
}

</table>